language: python
python:
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - 

# command to run tests and checks
script:
  - black --check ***.py
  # - python -m pytest --cov-report term --cov=utils/ test/